<a href="https://colab.research.google.com/github/jbelro82-prog/Especializaci-n_data_analytincs/blob/main/Sprint7_Jessica_Beltran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ALUMNE : JESSICA BELTRAN RODRIGUEZ

---

SPRINT 7

In [16]:
# importem llibreries que farem servir durant l'sprint

import pandas as pd

##***NIVELL 1***

##**Excercici 1: Selecció de Personal**

> *Tu treballes com a analista de dades en el departament de RRHH d'una empresa. S'ha obert una nova oferta laboral interna i l'empresa ha decidit que només les primeres 10 persones que s'inscriguin podran participar en el procés de selecció*

Per això, t'han encarregat desenvolupar una eina senzilla en Python que actuï com a formulari d'inscripció i sistema de classificació inicial. Aquest formulari ha de permetre introduir, per a cada candidat/a:

*   Nom i Cognoms
*   Telèfon de contacte
*   Anys d'experiència dins de l'empresa
*   Coneixement de Català (0–3 punts)
  
          *    0 = sense coneixement
          *    1 = fins a nivell B1
          *    2 = nivell B2
          *    3 = C1 o superior

*   Domini d'Excel (0–3 punts)

          *    0 = nivell bàsic
          *    1 = ús de funcions
          *    2 = taules dinàmiques
          *    3 = Visual Basic i Macros


*   Títol acadèmic (0–3 punts)

          *    0 = ESO
          *    1 = FP
          *    2 = Universitat
          *    3 = Màster o superior

Assegurant-se que tota la informació introduïda és correcta i entra dins els valors permesos. A partir d'aquestes dades, el programa haurà de calcular una puntuació total aplicant el pes de l'experiència (anys * 1.5) i sumant-hi els punts de català, excel i titulació, i a continuació classificar automàticament cada persona segons els llindars establerts per l'empresa:

*  Prioritat Alta → puntuació ≥ 12
*  Candidat adequat → 8 ≤ puntuació < 12
*  No prioritari → puntuació < 8

Cada vegada que algú complet a el formulari, s'ha de mostrar la seva puntuació individual. Quan ja s'hagin inscrit exactament deu persones, l'eina ha de deixar d'acceptar nous registres i generar un informe final en pantalla, ordenat primer segons la prioritat i, en cas d'empat, per la puntuació obtinguda. Aquest informe ha d'incloure el nom, el telèfon i la puntuació de cada candidat per tal que el departament de RRHH els pugui contactar ràpidament.


**Definició de l'Algorisme**

1.   Crear una funció per demanar dades a l'usuari. Aquesta funció interactua amb l'usuari i guarda les dades a les variables designades.
2.   Funció que rep les dades de l'usuari(variables) i les valida conforme als nostres paràmetres de validació. Retorna True o False en funció de si son correctes o no.

Validem dades i rangs:

*  Comprovem que el nom contingui lletres i eliminem espais.
*  El telèfon ha de ser tipus dígit i longitud de 9.
*  Les respostes de coneixements han d'estar dins dels rangs establerts, és a dir, entre 0 i 3.

3.   Càlcul de punts, la funció rep les dades validades de l'usuari i s'encarrega de retornar el punts calculats.

*   Càlcul de l'experiènica (anys * 1,5)
*   Suma de punts dels rangs de coneixements

4.   Classificació segons puntuació. Rep l'usuari amb els punts calculats i retorna l'usuari classificat segons prioritat obtinguda dels punts calculats.

Definirem una funció utilitzant els operadors condicionals if, elif i else per a poder classificar dins dels paràmetres establerts.

Paràmetres:

*   Prioritat alta --> puntuació >=12
*   Candidat adequat-->8 puntuació <12
*   No prioritari --> puntuació <8

5.   Mostrar resultats individuals rebent tota la informació de l'usuari amb els punts i la classificació.

Crearem una funció per a que ens retorni totes les dades
importants i definitives de l'usuari amb una llista:

*   Nom i cognom
*   Telèfon
*   Anys d'experiència
*   Coneixements de català
*   Domini d'Excel
*   Títol acadèmic
*   Classificació


7.   Mostrar informe. Rebem la llista d'usuaris i creem un informe amb els requisits de RRHH:

 >>nom

 >>telèfon

 >>puntuació de cada candidat

6.   main_selecció, funció principal que orquestrarà totes les anteriors. Pas previ a mostrar l'informe rebent la llista de tots els usuaris i els seus resultats.

In [2]:
llista_test = [
    "Laura Serra", "608112233", 6, 3, 3, 3,
    "Clara Gómez", "655221199", 3, 3, 3, 2,
    "Sergio López", "644112211", 3, 2, 2, 2,
    "Candidat Error", "611000000", 5, 7, 3, 2, # Català = 7 → NO VÀLID
    "Marta Ruiz", "699887766", 2, 3, 2, 1,
    "Marc Vidal", "612443322", 6, 3, 3, 3,
    "Júlia Romero", "677998877", 5, 3, 3, 2,
    "Pol Navarro", "699554433", 4, 3, 2, 2,
    "David Ferrer", "677665544", 2, 1, 1, 1,
    "Anna Paredes", "633221144", 1, 2, 1, 0,
    "Anibal Paredes", "644272727", 1, 2, 1, 0,
    "Núria Casals", "600112200", 8, 2, 3, 3 # 11è candidat
]

1-Demanar dades a l'usuari:

In [3]:
# Definim la funció per obtenir dades les dades dels candidats de la llista de test.

def obtenir_dades (llistat_usuaris):
   candidats_procesats = [] # creem una llista per als candidats processats
   i = 0 # indiquem la posició del primer element
   while i + 5 < len(llista_test):
     # bucle while per a que cada candidat tingui mínim 6 elements

     candidat = {
            "nom": llista_test[i],
            "telefon": llista_test[i+1],
            "anys_experiencia": llista_test[i+2],
            "coneixements_catala": llista_test[i+3],
            "domini_excel": llista_test[i+4],
            "titulacions": llista_test[i+5]
     }
     candidats_procesats.append(candidat) #guardem el candidat a la llista nova

     i+=6 #passem a la següent posició de la llista

   return candidats_procesats

In [4]:
# comporvem que la funció recull la llista de candidats inscrits correctament
candidats_procesats = obtenir_dades(llista_test)
print(candidats_procesats)

[{'nom': 'Laura Serra', 'telefon': '608112233', 'anys_experiencia': 6, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 3}, {'nom': 'Clara Gómez', 'telefon': '655221199', 'anys_experiencia': 3, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 2}, {'nom': 'Sergio López', 'telefon': '644112211', 'anys_experiencia': 3, 'coneixements_catala': 2, 'domini_excel': 2, 'titulacions': 2}, {'nom': 'Candidat Error', 'telefon': '611000000', 'anys_experiencia': 5, 'coneixements_catala': 7, 'domini_excel': 3, 'titulacions': 2}, {'nom': 'Marta Ruiz', 'telefon': '699887766', 'anys_experiencia': 2, 'coneixements_catala': 3, 'domini_excel': 2, 'titulacions': 1}, {'nom': 'Marc Vidal', 'telefon': '612443322', 'anys_experiencia': 6, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 3}, {'nom': 'Júlia Romero', 'telefon': '677998877', 'anys_experiencia': 5, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 2}, {'nom': 'Pol Navarro', 'telefon': '699554433', 'anys_experiencia': 4, 'coneixements_catala': 3, 'domini_excel': 2, 'titulacions': 2}, {'nom': 'David Ferrer', 'telefon': '677665544', 'anys_experiencia': 2, 'coneixements_catala': 1, 'domini_excel': 1, 'titulacions': 1}, {'nom': 'Anna Paredes', 'telefon': '633221144', 'anys_experiencia': 1, 'coneixements_catala': 2, 'domini_excel': 1, 'titulacions': 0}, {'nom': 'Anibal Paredes', 'telefon': '644272727', 'anys_experiencia': 1, 'coneixements_catala': 2, 'domini_excel': 1, 'titulacions': 0}, {'nom': 'Núria Casals', 'telefon': '600112200', 'anys_experiencia': 8, 'coneixements_catala': 2, 'domini_excel': 3, 'titulacions': 3}]

2.Validació de dades i rangs

In [5]:
# funció per a validar la llista dels candidats procesats

def validar_dades(candidats_procesats):

    candidats_filtrats = [] # creem nova llista per als candidats correctes
    i = 0

    while i < len(candidats_procesats): # fem un bucle per a que agafi tota la llista
        candidat = candidats_procesats[i] # indiquem la posició primera de la llista

        # validem tots els elements del diccionari de cada candidat
        if (candidat["nom"] != "" and
            str(candidat["telefon"]) != "" and
            candidat["anys_experiencia"] >= 0 and
            0 <= candidat["coneixements_catala"] <= 3 and
            0 <= candidat["domini_excel"] <= 3 and
            0 <= candidat["titulacions"] <= 3):

            candidats_filtrats.append(candidat) # afegim els correctes a la llista
            print(f"correcte ({len(candidats_filtrats)}/10): {candidat['nom']}")

            if len(candidats_filtrats) == 10:
                break # parem la validació quan arribem als 10
        else:
            print(f"incorrecte: {candidat['nom']}")
             # afegim incorrecte per als que deixem fora de la llista

        i += 1  # per a que sumi 1 a i cada vegada


    return candidats_filtrats

In [6]:
# comprovem el resultat de tots els candidats
resultat = validar_dades(candidats_procesats)
print(resultat)

correcte (1/10): Laura Serra
correcte (2/10): Clara Gómez
correcte (3/10): Sergio López
incorrecte: Candidat Error
correcte (4/10): Marta Ruiz
correcte (5/10): Marc Vidal
correcte (6/10): Júlia Romero
correcte (7/10): Pol Navarro
correcte (8/10): David Ferrer
correcte (9/10): Anna Paredes
correcte (10/10): Anibal Paredes
[{'nom': 'Laura Serra', 'telefon': '608112233', 'anys_experiencia': 6, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 3}, {'nom': 'Clara Gómez', 'telefon': '655221199', 'anys_experiencia': 3, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 2}, {'nom': 'Sergio López', 'telefon': '644112211', 'anys_experiencia': 3, 'coneixements_catala': 2, 'domini_excel': 2, 'titulacions': 2}, {'nom': 'Marta Ruiz', 'telefon': '699887766', 'anys_experiencia': 2, 'coneixements_catala': 3, 'domini_excel': 2, 'titulacions': 1}, {'nom': 'Marc Vidal', 'telefon': '612443322', 'anys_experiencia': 6, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 3}, {'nom': 'Júlia Romero', 'telefon': '677998877', 'anys_experiencia': 5, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 2}, {'nom': 'Pol Navarro', 'telefon': '699554433', 'anys_experiencia': 4, 'coneixements_catala': 3, 'domini_excel': 2, 'titulacions': 2}, {'nom': 'David Ferrer', 'telefon': '677665544', 'anys_experiencia': 2, 'coneixements_catala': 1, 'domini_excel': 1, 'titulacions': 1}, {'nom': 'Anna Paredes', 'telefon': '633221144', 'anys_experiencia': 1, 'coneixements_catala': 2, 'domini_excel': 1, 'titulacions': 0}, {'nom': 'Anibal Paredes', 'telefon': '644272727', 'anys_experiencia': 1, 'coneixements_catala': 2, 'domini_excel': 1, 'titulacions': 0}]

3.Càlcul de punts

In [7]:
# definim funció per obtenir el càlcul de punts per candidat
def calcular_punts(candidat):

  punts_totals = (
      candidat["anys_experiencia"] * 1.5 +
      candidat["coneixements_catala"] +
      candidat["domini_excel"] +
      candidat["titulacions"]
  )
  candidat["puntuació"] = punts_totals # afegim puntuació al diccionari del candidat

  return punts_totals

In [8]:
# comprovem funció amb el primer candidat
punts_candidat_1= calcular_punts(candidats_procesats[0])
print(punts_candidat_1)

18.0

4.Classificació segons puntuació

In [9]:
# definim la funció per a classificar al candidat amb els paràmetres establerts i l'afegim al seu diccionari.

def classificar_usuari(candidat):

    punts_totals = candidat["puntuació"] #li diem que agafi la puntuació

    if punts_totals >= 12:
        classificacio = "Prioritat alta"
    elif punts_totals >= 8:
        classificacio = "Candidat adequat"
    else:
        classificacio = "No prioritari"

    candidat["classificacio"] = classificacio # l'afegim al diccionari

    return classificacio

In [10]:
# comprovem amb el candidat_1
classificacio_candidat_1 = classificar_usuari(candidats_procesats[0]) # li pasem el diccionar del candidat amb tots els elements per a que el mostri
print(candidats_procesats[0])

{'nom': 'Laura Serra', 'telefon': '608112233', 'anys_experiencia': 6, 'coneixements_catala': 3, 'domini_excel': 3, 'titulacions': 3, 'puntuació': 18.0, 'classificacio': 'Prioritat alta'}

5.Mostrar resultats individuals

In [11]:
# definim la funció per a mostrar els resultats individuals del candidat

def mostrar_resultat(candidat):
  # fem un print i afegim tots els elements del diccionari per a que els pugui mostrar de forma llegible
    print(f"Nom i cognom: {candidat['nom']},\nTelèfon: {candidat['telefon']},\nAnys d'experiència: {candidat['anys_experiencia']},\nConeixements de català: {candidat['coneixements_catala']},\nDomini d'Excel: {candidat['domini_excel']},\nTítol acadèmic: {candidat['titulacions']},\nPuntuació: {candidat['puntuació']},\nClassificació: {candidat['classificacio']}\n")

In [12]:
# cridem a la funció per a mostrar l'informe individual del primer candidat procesat amb tota la informació actualitzada (punts i classificació)

mostrar_resultat(candidats_procesats[0])

Nom i cognom: Laura Serra,
Telèfon: 608112233,
Anys d'experiència: 6,
Coneixements de català: 3,
Domini d'Excel: 3,
Títol acadèmic: 3,
Puntuació: 18.0,
Classificació: Prioritat alta

6.Funció principal.

In [13]:
# definim la funció principal que orquestri totes les altres

def main_seleccio(llista_test):
     # cridem a totes les funcions
    candidats_procesats = obtenir_dades(llista_test)
    candidats_procesats = validar_dades(candidats_procesats)

    for candidat in candidats_procesats: # bucle per als càlculs de cada candidat dins la llista de candidats proces
        calcular_punts(candidat)
        classificar_usuari(candidat)
        mostrar_resultat(candidat)

    df = pd.DataFrame(candidats_procesats)

    df_final = df.sort_values(by=['puntuació', 'classificacio'], ascending=[False, True]) # endreçem els valors de puntuació i classificació de major a menor

    return df_final



7.Mostrar informe final per RRHH.

A tenir en compte per generar l'informe:

Ordenació doble: Primer per la prioritat (de més alta a més baixa) i, si empaten, per la puntuació més alta.

Presentació visual: Mostrar-ho net, en format taula, perquè RRHH ho llegeixi ràpid

In [14]:
# mostrem el dataframe final endreçat per

df_resultat = main_seleccio(llista_test)
display(df_resultat)

correcte (1/10): Laura Serra
correcte (2/10): Clara Gómez
correcte (3/10): Sergio López
incorrecte: Candidat Error
correcte (4/10): Marta Ruiz
correcte (5/10): Marc Vidal
correcte (6/10): Júlia Romero
correcte (7/10): Pol Navarro
correcte (8/10): David Ferrer
correcte (9/10): Anna Paredes
correcte (10/10): Anibal Paredes
Nom i cognom: Laura Serra,
Telèfon: 608112233,
Anys d'experiència: 6,
Coneixements de català: 3,
Domini d'Excel: 3,
Títol acadèmic: 3,
Puntuació: 18.0,
Classificació: Prioritat alta

Nom i cognom: Clara Gómez,
Telèfon: 655221199,
Anys d'experiència: 3,
Coneixements de català: 3,
Domini d'Excel: 3,
Títol acadèmic: 2,
Puntuació: 12.5,
Classificació: Prioritat alta

Nom i cognom: Sergio López,
Telèfon: 644112211,
Anys d'experiència: 3,
Coneixements de català: 2,
Domini d'Excel: 2,
Títol acadèmic: 2,
Puntuació: 10.5,
Classificació: Candidat adequat

Nom i cognom: Marta Ruiz,
Telèfon: 699887766,
Anys d'experiència: 2,
Coneixements de català: 3,
Domini d'Excel: 2,
Títol acadèmic: 1,
Puntuació: 9.0,
Classificació: Candidat adequat

Nom i cognom: Marc Vidal,
Telèfon: 612443322,
Anys d'experiència: 6,
Coneixements de català: 3,
Domini d'Excel: 3,
Títol acadèmic: 3,
Puntuació: 18.0,
Classificació: Prioritat alta

Nom i cognom: Júlia Romero,
Telèfon: 677998877,
Anys d'experiència: 5,
Coneixements de català: 3,
Domini d'Excel: 3,
Títol acadèmic: 2,
Puntuació: 15.5,
Classificació: Prioritat alta

Nom i cognom: Pol Navarro,
Telèfon: 699554433,
Anys d'experiència: 4,
Coneixements de català: 3,
Domini d'Excel: 2,
Títol acadèmic: 2,
Puntuació: 13.0,
Classificació: Prioritat alta

Nom i cognom: David Ferrer,
Telèfon: 677665544,
Anys d'experiència: 2,
Coneixements de català: 1,
Domini d'Excel: 1,
Títol acadèmic: 1,
Puntuació: 6.0,
Classificació: No prioritari

Nom i cognom: Anna Paredes,
Telèfon: 633221144,
Anys d'experiència: 1,
Coneixements de català: 2,
Domini d'Excel: 1,
Títol acadèmic: 0,
Puntuació: 4.5,
Classificació: No prioritari

Nom i cognom: Anibal Paredes,
Telèfon: 644272727,
Anys d'experiència: 1,
Coneixements de català: 2,
Domini d'Excel: 1,
Títol acadèmic: 0,
Puntuació: 4.5,
Classificació: No prioritari

,nom,telefon,anys_experiencia,coneixements_catala,domini_excel,titulacions,puntuació,classificacio
0,Laura Serra,608112233,6,3,3,3,18.0,Prioritat alta
4,Marc Vidal,612443322,6,3,3,3,18.0,Prioritat alta
5,Júlia Romero,677998877,5,3,3,2,15.5,Prioritat alta
6,Pol Navarro,699554433,4,3,2,2,13.0,Prioritat alta
1,Clara Gómez,655221199,3,3,3,2,12.5,Prioritat alta
2,Sergio López,644112211,3,2,2,2,10.5,Candidat adequat
3,Marta Ruiz,699887766,2,3,2,1,9.0,Candidat adequat
7,David Ferrer,677665544,2,1,1,1,6.0,No prioritari
8,Anna Paredes,633221144,1,2,1,0,4.5,No prioritari
9,Anibal Paredes,644272727,1,2,1,0,4.5,No prioritari

**Conclusions:**

Aquest exercici ens permet treballar amb un dataset de forma ràpida i eficient per per validar, calcular i classificar candidats per una selecció de RRHH.
L'informe final, ens permet veure la classificació d'usuaris amb la puntuació obtinguda i la prioritat de contacte de forma visual i clara.Per tant, els usuaris queden categoritzats ràpidament per a ser contactats segons els criteris establerts. Sent els primers de prioritat alta i els últims no prioritari.
Aquest informe, estalvia recursos a l'hora de fer la selecció de candidats, tant de temps de personal com de cribatge.

##**Exercici 2: Segmentació per risc de cistella de compra**

*Treballes com a analista de dades al departament de Màrqueting Digital. L'empresa vol millorar l'efectivitat de les campanyes de recuperació de cistellas de compra abandonats i necessita identificar quins clients tenen més risc d'abandonament, quin segment de comportament presenten i quin missatge publicitari és el més adequat per a cadascun.*

Disposes d'un conjunt de dades amb informació bàsica de 10 clients:


*   id_client
*   nom
*   edat
*   grup_edat
*   codi_comportament


» Codis de comportament

0 → Navega però no afegeix productes

1 → Afegeix productes però no arriba al checkout

2 → Arriba al checkout però no paga

3 → Cistella de compra abandonat fa menys de 24 h

4 → Cistella de compra abandonat fa més de 24 h

» Factors segons codi de comportament
Codi 0 → 0.10
Codi 1 → 0.25
Codi 2 → 0.50
Codi 3 → 0.75
Codi 4 → 0.90

» Factors segons grup d'edat
18–25 → 1.20
26–40 → 1.00
41–60 → 0.85
60+ → 0.70

» Fórmula del risc final
risc_final = factor codi * factor edat

Un cop processats els clients, has de ser capaç de respondre:

» 1. Quins clients s'han de contactar primer en una campanya de retargeting?

» 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?)

» 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?

» 4. Quin client seria el més rendible de recuperar?

Interpretant el risc final i el segment.

⚙️ Requisits tècnics del teu programa
Hauràs de construir un sistema modular utilitzant diverses funcions i, sobretot, sense utilitzar if/elif/else per fer la segmentació.

✅ Resultat esperat
Un DataFrame o diccionari final amb:

id_cliente
nombre
edad
grupo_edad
codigo_comportamiento
segment
missatge
factor_codi
factor_edat
risc_final
I capacitat per respondre totes les preguntes de màrqueting demanades en una funció.

**Definició de l'algorisme**

1. Tenim una llista de clients amb dades de 10 clients (diccionari)

Crearem diccionaris per les dades (edat_factor i codi_factor)

>diccionari d'edat i factor: ens permetrà poder classificar per grups d'edat i obtenir de manera ràpida el seu factor per poder fer el càlcul del risc

>diccionari de comportament i factor: aquest ens permet obtenir el codi de coportament i el seu factor corresponent.Afegirem el missatge per marketing.

2.Processar_clients:
Crearem una funció per calcular les dades dels clients que faci el següent:

obtenir_segment_i_factor

obtenir_edat

calcular_risc

La funció rep, el diccionari de diccionaris de clients (dades)
Calcularem els factors demanats i els guardarem dins del diccionari de cada client fent servir les funcions següents: Un bucle que recorre el diccionari principal i executa les funcions per cada client
Ens retornarà un diccionari de diccionaris de clients
+ obtenir_segment_i_factor:
Rep diccionari de 1 client,calcula segment i factor i afegeix les dades al mateix diccionari del client.Ens retorna un diccionari del client amb els nous camps i valors calculats

+ obtenir_factor_edat:  
Rep el diccionari de 1 client,calcula factor_edat i afegeix les dades al mateix diccionari del client.Retorna el diccionari del client amb els nous camps i valors calculats

+ calcular_risc:  
Rep el diccionari de 1 client,calcula risc i afegeix les dades al mateix diccionari del client.Retorna diccionari del client amb els nous camps calculats

 Fórmula del risc final
risc_final = factor codi * factor edat

3.Mostrar i respondre preguntes

Crearem una una funció per mostrar les respostes, aquesta funció rep el dataframe clients on tenim tota la informació relativa als clients ja processada.Calcularem les diferents opcions per obtenir-ne la millor resposta de cada pregunta i en mostrarem els resultats obtinguts en format taula amb un dataframe.

Preguntes a respondre:

» 1. Quins clients s'han de contactar primer en una campanya de retargeting?  

» 2. Quines diferències hi ha entre clients amb el mateix comportament però d'edats diferents? (Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?):
dins de les coincidencies de comportament

» 3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?

» 4. Quin client seria el més rendible de recuperar?

4.Deficició de la funció principal que orquestrará totes les altres.
Aquesta funció endreçarà de majora menor el factor de risc, mostrarà les respostes en dataframe i converteix a pandas el dataframe final.

5.Mostrar dataframe.

Es mostrán les preguntes i resposta i el diccionari de clients convertits a dataframe.

dades demanades pel dataframe:

id_cliente

nom

edat

grup_edat

codi_comportament

segment

missatge

codi_factor

edat_factor

risc_final

In [40]:
#llista de diccionaris de clients

clients = [
    {"id_client": 1, "nom": "Laura Serra", "edat": 23, "grup_edat": "18-25", "codi_comportament": 4},
    {"id_client": 2, "nom": "Marc Vidal", "edat": 35, "grup_edat": "26-40", "codi_comportament": 3},
    {"id_client": 3, "nom": "Ana López", "edat": 29, "grup_edat": "26-40", "codi_comportament": 2},
    {"id_client": 4, "nom": "Joan Riera", "edat": 19, "grup_edat": "18-25", "codi_comportament": 2},
    {"id_client": 5, "nom": "Mónica Pérez", "edat": 47, "grup_edat": "41-60", "codi_comportament": 4},
    {"id_client": 6, "nom": "Luis García", "edat": 52, "grup_edat": "41-60", "codi_comportament": 1},
    {"id_client": 7, "nom": "Pilar Sánchez", "edat": 61, "grup_edat": "60+", "codi_comportament": 3},
    {"id_client": 8, "nom": "Eva Martín", "edat": 38, "grup_edat": "26-40", "codi_comportament": 0},
    {"id_client": 9, "nom": "Diego Romero", "edat": 24, "grup_edat": "18-25", "codi_comportament": 1},
    {"id_client": 10, "nom": "Núria Costa", "edat": 33, "grup_edat": "26-40", "codi_comportament": 4}
]

1.Creem els diccionaris d'edat_factor i comportament_factor:

In [41]:
#diccionari on tenim l'edat i el factor segons el grup d'edat dels clients

edat_factor = {
"18-25": 1.20,
 "26-40": 1.00,
 "41-60": 0.85,
 "60+": 0.70
}

In [42]:
#diccionari per comportament i factor i dins d'aquest un diccionari per a cada codi amb el factor,segment i el missatge. D'aquesta manera ho podem tenir tot en un mateix diccionari de diccionaris.

codi_factor = {
 0:{
    "factor":0.10,
    "segment":"Navega però no afegeix productes",
    "missatge":"Has vist les novetats? Fes una ullada!"
  },
  1:{
    "factor":0.25,
    "segment":"Afegeix productes però no arriba al checkout",
    "missatge":"Completa la teva compra i rebràs un 5% de descompte"
  },
  2:{
      "factor": 0.50,
      "segment":"Arriba al checkout però no paga",
      "missatge":"Aprofita els enviaments gratuits."
  },
  3: {
      "factor": 0.75,
      "segment":"Cistella de compra abandonat fa menys de 24h",
      "missatge":"Finalitza la teva compra i emporta't un regal assegurat"
    },
   4: {
      "factor": 0.90,
      "segment": "Cistella de compra abandonat fa més de 24 h",
      "missatge": "Última oportunitat! 10% de descompte nomès avui! Aprofita!"
    },
}

2.Processar clients.

In [47]:
# definim la funció per calcular les dades dels clients i poder-los porcesar

def calcular_dades_clients(dades_clients):
    for client in dades_clients: # bucle que recorre tots els clients
        codi = client["codi_comportament"]

        # obtenim segment i factor i l'afegim al diccionari com a nous elements
        client["factor_codi"] = codi_factor[codi]["factor"]
        client["segment"] = codi_factor[codi]["segment"]
        client["missatge"] = codi_factor[codi]["missatge"]

        # obtenim factor edat i l'afegim al diccionari
        grup = client["grup_edat"]
        client["factor_edat"] = edat_factor[grup]

        # calculem risc final i l'afegim al diccionari
        client["risc_final"] = round(client["factor_codi"] * client["factor_edat"], 2)

    return dades_clients

In [48]:
# comprovem que la funció afegeix els nous elements

resultat_comprovacio = calcular_dades_clients(clients)
print(resultat_comprovacio[0])

{'id_client': 1, 'nom': 'Laura Serra', 'edat': 23, 'grup_edat': '18-25', 'codi_comportament': 4, 'factor_codi': 0.9, 'segment': 'Cistella de compra abandonat fa més de 24 h', 'missatge': 'Última oportunitat! 10% de descompte nomès avui! Aprofita!', 'factor_edat': 1.2, 'risc_final': 1.08}

3.Mostrar respostes

In [49]:
# definim una funció que ens mostrará les preguntes i les respostes donat wl nostre criteri i càlculs.

def mostrar_respostes(dfclients):
    # Pregunta 1
    print("\n\n1. Quins clients s'han de contactar primer en una campanya de retargeting?")
    print("- S'ha establert la classificació en tres trams sobre el factor final de risc en Alt, mitjà i baix,\n  i es proposa contactar amb els clients de classificació de risc Alt")
    limits = [0, 0.29, 0.60, 2] # fixem uns límits per categoritzar
    labels = ["baix", "mitja", "alt"] #posem etiquetes a la classificació
    # fem servir el mètode cut per agrupar les dades numèriques dels intervals fixats
    dfclients["class_risc"] = pd.cut(dfclients["risc_final"], bins=limits, labels=labels)
    resposta_1 = dfclients[dfclients["class_risc"] == "alt"]
    display(resposta_1)

    # Pregunta 2
    print("\n\n2. Quines diferències hi ha entre clients amb el mètode comportament però d'edats diferents?\n(Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?):")
    print("- Tot i tenir el mateix comportament, hi ha una gran diferència en el factor de risc inversament proporcional a l'edat ")
    # endreçem per codi de comportament
    resposta_2 = dfclients.sort_values(by='codi_comportament')
    display(resposta_2)

    # Pregunta 3
    print("\n\n3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?")
    print("- Els clients amb un factor de risc baix no presenten urgència d'acció:")
    # mostrem els de risc baix
    resposta_3 = dfclients[dfclients["class_risc"] == "baix"]
    display(resposta_3)

    # Pregunta 4
    print("\n\n4. Quin client seria el més rendible de recuperar?")
    print("- Els clients més rendibles de recuperar són els que abandonen el procés de compra un cop afegits productes a la cistella,\n  amb i sense checkout, i entre franges d'edat de 26 a 60, ja que es considera que tenen un\n  procés de compra madurat i no tant impulsivament com la franja més jove ")
    # filtrem per codi 1,2,3 i grup de edat de 26-40
    resposta_4 = dfclients[(dfclients["codi_comportament"] >= 1) & (dfclients["codi_comportament"] <= 3) & (dfclients["grup_edat"] == "26-40")]
    display(resposta_4)

4. Funció principal

In [50]:
# definim la funció principal

def main_marketing(clients):
    # afegim calcular dades per a que calculi tots els clients
    dades_procesades = calcular_dades_clients(clients)

    # convertim el dataframe a pandes
    dfclients = pd.DataFrame(dades_procesades)

    # endreçem de majora a menor risc el dataframe
    dfclients = dfclients.sort_values(by='risc_final', ascending=False)

    # afegim mostrar respostes
    mostrar_respostes(dfclients)

    # capçalera per al dataframe final
    print("\n\n--- 📊 DATA FRAME GENERAL DELS CLIENTS ---")
    display(dfclients)

5. Mostrem dataframe final i respostes

In [51]:
# cridem a la funció principal per a que mostri les preguntes i respostes i el dataframe endreçat

main_marketing(clients)

1. Quins clients s'han de contactar primer en una campanya de retargeting?
- S'ha establert la classificació en tres trams sobre el factor final de risc en Alt, mitjà i baix,
  i es proposa contactar amb els clients de classificació de risc Alt

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,1.20,1.08,alt
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,1.00,0.90,alt
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,0.85,0.77,alt
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24h,Finalitza la teva compra i emporta't un regal ...,1.00,0.75,alt

2. Quines diferències hi ha entre clients amb el mètode comportament però d'edats diferents?
(Per exemple: un client jove que abandona la cistella de compra fa 24 h té el mateix risc que un de més edat?):
- Tot i tenir el mateix comportament, hi ha una gran diferència en el factor de risc inversament proporcional a l'edat

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,Has vist les novetats? Fes una ullada!,1.00,0.10,baix
8,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,Completa la teva compra i rebràs un 5% de desc...,1.20,0.30,mitja
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Completa la teva compra i rebràs un 5% de desc...,0.85,0.21,baix
3,4,Joan Riera,19,18-25,2,0.50,Arriba al checkout però no paga,Aprofita els enviaments gratuits.,1.20,0.60,mitja
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Aprofita els enviaments gratuits.,1.00,0.50,mitja
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24h,Finalitza la teva compra i emporta't un regal ...,1.00,0.75,alt
6,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonat fa menys de 24h,Finalitza la teva compra i emporta't un regal ...,0.70,0.52,mitja
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,0.85,0.77,alt
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,1.00,0.90,alt
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,1.20,1.08,alt

3. Quins clients presenten tan poc interès que no val la pena invertir-hi pressupost?
- Els clients amb un factor de risc baix no presenten urgència d'acció:

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Completa la teva compra i rebràs un 5% de desc...,0.85,0.21,baix
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,Has vist les novetats? Fes una ullada!,1.00,0.10,baix

4. Quin client seria el més rendible de recuperar?
- Els clients més rendibles de recuperar són els que abandonen el procés de compra un cop afegits productes a la cistella,
  amb i sense checkout, i entre franges d'edat de 26 a 60, ja que es considera que tenen un
  procés de compra madurat i no tant impulsivament com la franja més jove

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24h,Finalitza la teva compra i emporta't un regal ...,1.0,0.75,alt
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Aprofita els enviaments gratuits.,1.0,0.50,mitja

--- 📊 DATA FRAME GENERAL DELS CLIENTS ---

,id_client,nom,edat,grup_edat,codi_comportament,factor_codi,segment,missatge,factor_edat,risc_final,class_risc
0,1,Laura Serra,23,18-25,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,1.20,1.08,alt
9,10,Núria Costa,33,26-40,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,1.00,0.90,alt
4,5,Mónica Pérez,47,41-60,4,0.90,Cistella de compra abandonat fa més de 24 h,Última oportunitat! 10% de descompte nomès avu...,0.85,0.77,alt
1,2,Marc Vidal,35,26-40,3,0.75,Cistella de compra abandonat fa menys de 24h,Finalitza la teva compra i emporta't un regal ...,1.00,0.75,alt
3,4,Joan Riera,19,18-25,2,0.50,Arriba al checkout però no paga,Aprofita els enviaments gratuits.,1.20,0.60,mitja
6,7,Pilar Sánchez,61,60+,3,0.75,Cistella de compra abandonat fa menys de 24h,Finalitza la teva compra i emporta't un regal ...,0.70,0.52,mitja
2,3,Ana López,29,26-40,2,0.50,Arriba al checkout però no paga,Aprofita els enviaments gratuits.,1.00,0.50,mitja
8,9,Diego Romero,24,18-25,1,0.25,Afegeix productes però no arriba al checkout,Completa la teva compra i rebràs un 5% de desc...,1.20,0.30,mitja
5,6,Luis García,52,41-60,1,0.25,Afegeix productes però no arriba al checkout,Completa la teva compra i rebràs un 5% de desc...,0.85,0.21,baix
7,8,Eva Martín,38,26-40,0,0.10,Navega però no afegeix productes,Has vist les novetats? Fes una ullada!,1.00,0.10,baix

**Conclusions:**

Aquest excercici ens permet tenir els clients segmentats i classificats segons el nivell de risc de pèrdua de client/venda.
El fet de poder visualitzar la classificació de risc i segment alhora, ens serveix per poder extraure un anàlisis dels nostres clients basant-nos en dades i poder analitzar el seu comportament, relació amb el grup d'edat i el risc.
Aquesta classificació ens ajuda a saber on destinará recursos el departament de marketing. Análisis final:

Podem concloure que, a igualtat de comportament, un jove sempre tindrà més risc de perdre's definitivament. Els joves són més impulsius: si abandonen la cistella, és molt probable que hagin vist una altra cosa a RRSS o a la competència i es canviïn de marca en cinc minuts. En canvi, la gent gran (60+) és més fidel o es pren el seu temps; el seu risc és més baix perquè el fet que hagin marxat no significa necessàriament que no tornin demanà.
D'altre banda, veiem que, un codi 2 (arribar al checkout) o un codi 3/4 (abandonar la cistella) tenen factors molt alts (0.50, 0.75, 0.90) perquè el client ha fet tot el camí i s'ha fet enrere a l'últim segon.Per això considerem que s'ha de fer major esforç en aquests clients ja que, mostren una intenció clara de compra i amb els misstges adecuats no es refredaria el procès.
Així que la relació és clara: el comportament ens diu com de calenta està la venda, i l'edat ens diu a quina velocitat es refredarà si no fem res.

# **NIVELL 2**

##**Exercici 1 Gestió de risc i priorització de pacients**

> Treballes com a analista de dades en un centre mèdic especialitzat. Diversos pacients han enviat els seus símptomes a través d'un formulari online, però les dades arriben en un format desordenat i poc estructurat, i l'equip mèdic necessita que els organitzis per poder prioritzar l'ordre d'atenció segons la gravetat.


🎯 Objectius
L'objectiu és transformar aquestes dades en informació útil per als metges. A partir dels registres en brut, has de:

» Convertir cada string en una estructura neta (diccionari o similar).

» Separar i normalitzar la llista de

símptomes:

minúscules

eliminar espais

dividir correctament per comes

» Assignar un risc a cada símptoma

utilitzant el diccionari nivells_risc.

» Calcular el risc total de cada pacient

sumant els valors.

» Ordenar els pacients de major a menor
risc per determinar la prioritat d'atenció.


✅ Resultat esperat
Un DataFrame o un diccionari amb:

nom
edat
símptomes normalitzats
risc_total
I un apartat final amb els pacients ordenats per prioritat (més risc → primer).

In [23]:
#llista amb informació de pacients

pacients = [
    "Maria|45|tos, Fiebre Alta, dolor_pecho",
    "Luis|33|dolor_cabeza,faTiga",
    "Sara|67|fiebre alta, dificultad RESPIRAR, tos",
    "Jordi|52|fatiga , tos",
    "Anna|29|fiebre alta,dolor_cabeza"
]

In [24]:
#diccionari de nivell de riscs

nivells_risc = {
    "fiebre_alta": 3,
    "dificultad_respirar": 5,
    "dolor_pecho": 4,
    "tos": 1,
    "fatiga": 1,
    "dolor_cabeza": 1
}

**Definició de l'Algorisme**

1.Crearem una funció per netejar dades def netejar_dades. Aquesta funció rebrà la llista de pacients i farà el següent:



*   Normalitzar dades: convertir en minúscula les lletres, eliminar espais, treure les barres separadores i separar les paraules correctament amb una coma.

Aquesta funció retornarà un diccionari dels pacients normalitzat per a poder treballar les dades correctament.

2.Crear una funció per assignar un risc a cada símptoma utilitzant el diccionari de pacients i nivells_risc.Rep un pacient i retorna un pacient amb el seu risc al diccionari.

3.Funció per calcular el risc total de cada pacient sumant els valors.Aquesta funció rep el diccionari de pacients i fa la suma dels valors del nivell de risc.Retorna la suma al camp "risc_total" i l'afegeix al diccionari del pacient.

4.Endreçar el pacient de majora a menor risc i convertir-ho a dataframe.

5.Crear la funció principal que orquestri totes les altres

Mostrar resultats en format taula en un dataframe que compleixi els següents requisits:

<<nom

<<edat

<<símptomes normalitzats

<<risc_total

<<apartat final amb els pacients ordenats per prioritat (més risc → primer).

1. Creeem la funció per netejar les dades dels pacients.

In [25]:
# definim la funció per netejar les dades dels pacients
def netejar_dades (pacients_llista_neta):

  pacients_procesats = [] #nova llista per als pacients procesats

  # bucle per netejar les dades
  for pacient_str in pacients_llista_neta:

    parts = pacient_str.split('|')
    nom = parts[0].strip()
    edat = int(parts[1].strip())

    simptomes_original_str = parts[2].strip()
    simptomes_lower_str = simptomes_original_str.lower()

    simptomes_list_format = [s.strip() for s in simptomes_lower_str.split(',')]
    simptomes = [s.replace(' ', '_') for s in simptomes_list_format]

    pacient_dict = {
        "nom": nom,
        "edat": edat,
        "simptomes": simptomes,
    }
    pacients_procesats.append(pacient_dict)

  return pacients_procesats

2. Funció asignar sic

In [26]:
# Definim la funció per assignar el risc a cada símptoma d'un pacient
def assignar_risc_simptomes(un_pacient, llistat_riscos):
    riscos_simptomes = []
    for simptoma in un_pacient['simptomes']:
        # Obtenim el risc o 0 si el símptoma no és a la llista
        riscos_simptomes.append(llistat_riscos.get(simptoma, 0))

    un_pacient['riscos_simptomes'] = riscos_simptomes
    return un_pacient

3. Calcular risc dels pacients

In [27]:
def calcular_risc_total(un_pacient):
    # Sumem els números de la llista 'riscos_simptomes' d'aquest pacient concret
    un_pacient['risc_total'] = sum(un_pacient['riscos_simptomes'])

    # Retornem el pacient sencer modificat
    return un_pacient

4. Funció ordenar pacients

In [28]:
def ordenar_pacients(llista_pacients):
    df_pacients = pd.DataFrame(llista_pacients)
    df_ordenat = df_pacients.sort_values(by='risc_total', ascending=False)
    return df_ordenat

5.Crear la funció principal que orquestri totes les altres i mostrar dataframe

In [30]:

# definim funció principal
def main_pacients(pacients, nivells_risc):
    # Pas 1: Netegem les dades (retorna llista de diccionaris)
    pacients_procesats = netejar_dades(pacients)

    # assignem el risc i calculem el total modificant els diccionaris
    for pacient in pacients_procesats:
        assignar_risc_simptomes(pacient, nivells_risc)
        calcular_risc_total(pacient)

    # cridem a la funció que converteix a DataFrame i ordena
    pacients_ordenats_df = ordenar_pacients(pacients_procesats)

    return pacients_ordenats_df


# Cridem la funció principal per obtenir directament el DataFrame ordenat
df_pacients = main_pacients(pacients, nivells_risc)

# Triem les columnes que volem tractar
df_taula = df_pacients[['nom', 'edat', 'simptomes', 'risc_total']].copy()
df_taula.columns = ['nom', 'edat', 'símptomes normalitzats', 'risc_total']



# Ajuntem les llistes amb comes i canviem els guions de forma segura
df_taula['símptomes normalitzats'] = df_taula['símptomes normalitzats'].apply(
    lambda x: ', '.join(x).replace('_', ' ')
)

# Funció per afegir les boletes dels colors del semàfor
def obtenir_bolita_risc(risc):
    if risc <= 3:
        return "🟢"
    elif risc <= 7:
        return "🟡"
    else:
        return "🔴"

# Creem la nova columna nivell de risc
df_taula['nivell de risc'] = df_taula['risc_total'].apply(obtenir_bolita_risc)


# afegim semàfor de colors per assignar el risc
print("PACIENTS ORDENATS PER PRIORITAT DE RISC")
print("Llegenda: 🔴 Alt (Risc > 7)  |  🟡 Mig (Risc 4-7)  |  🟢 Baix (Risc 0-3)")
print("-" * 75)

# Triem les columnes finals i les mostrem
columnes_finals = ['nom', 'edat', 'símptomes normalitzats', 'risc_total', 'nivell de risc']
display(df_taula[columnes_finals])

PACIENTS ORDENATS PER PRIORITAT DE RISC
Llegenda: 🔴 Alt (Risc > 7)  |  🟡 Mig (Risc 4-7)  |  🟢 Baix (Risc 0-3)
---------------------------------------------------------------------------

,nom,edat,símptomes normalitzats,risc_total,nivell de risc
2,Sara,67,"fiebre alta, dificultad respirar, tos",9,🔴
0,Maria,45,"tos, fiebre alta, dolor pecho",8,🔴
4,Anna,29,"fiebre alta, dolor cabeza",4,🟡
1,Luis,33,"dolor cabeza, fatiga",2,🟢
3,Jordi,52,"fatiga, tos",2,🟢

**Conclusions:**

Amb la realització d'aquest excercici hem aconseguit obtenir un dataframe endreçat, classificat i molt visual de pacients, símptomes i classificació per nivell de risc.
D'aquesta manera, es converteix en una eina molt valuosa per als serveis mèdics i el departament de triatge ja que, s'estalvia temps d'espera del pacient i s'optimitzen els recursos del servei sanitari.
He afegit el semàfor amb una altre columna de classificació segons el nivell de risc per obtenir una visualització mes clara per al triatge.

##**Exercici 2: Classificació de clients de segurs**



> Treballes com a analista de dades en una companyia asseguradora.
L'empresa vol calcular el risc dels clients, el preu estimat de la pòlissa i la probabilitat de frau, utilitzant un codi de comportament que ha estat generat per un model intern.


Tens la següent llista de clients:

In [18]:
# llista de clients

clients = [
    {"nom": "Ana", "edat": 42, "codi": 0},
    {"nom": "Carlos", "edat": 30, "codi": 2},
    {"nom": "Isabel", "edat": 55, "codi": 3},
    {"nom": "Jorge", "edat": 40, "codi": 1},
    {"nom": "Marta", "edat": 28, "codi": 0}
]

I aquest diccionari amb les categories del sistema

In [19]:
# diccionari amb nivells de seguro

nivells_seguro = {
    0: {"categoria": "Baix risc", "preu_base": 120, "frau": 0.01},
    1: {"categoria": "Risc mitjà", "preu_base": 200, "frau": 0.05},
    2: {"categoria": "Risc alt", "preu_base": 350, "frau": 0.15},
    3: {"categoria": "Risc crític", "preu_base": 500, "frau": 0.30}
}

El preu final s'ha de calcular amb la fórmula:

preu_final = preu_base * (1 + edat/100)
🎯 Objectius
» Classificar cada client utilitzant nivells_seguro (sense if/elif).
» Afegir:
La categoria
El preu base
La probabilitat de frau

» Calcular el preu final de la pòlissa amb la fórmula donada.

» Crear un DataFrame o diccionari amb la informació final.

» Ordenar els clients:
Per probabilitat de frau (descendent).
Per preu final.

✅ Resultat esperat
Un DataFrame o un diccionari amb:

Nom

Edat

Categoria

Preu_base

Preu_final

Probabilitat_frau

Un apartat d'anàlisi on s'indiqui:

Quin client té més probabilitat de frau

Quin té el preu final més alt

Qui seria prioritari de revisar manualment

**Definició Algorisme**

1.Hem de definir una funció per obtenir les dades que necessitem del diccionari de clients (edat i codi). Aquesta funció rep diccionari de client i nivells de seguro, afegeix la categoria, el preu base i la probabilitat de frau a la informació del client com a columnes noves.

2.Aquesta funció rep el diccionari del client (que ja està actualitzat amb el preu base). Aquesta funció aplica la fórmula matemàtica preu_base×(1+edat/100) per calcular l'import final de la pòlissa, afegeix aquest valor directament al client com a 'preu_final' (arrodonint a dos decimals) i el retorna.

3.Definim una funció principal que orquestri les altres.

4.Mostrar el dataframe ordenat per probabilitat de frau i preu.
  
Mostrar anàlisis i conclusions basant-nos en les següents preguntes:

Quin client té més probabilitat de frau

Quin té el preu final més alt

Qui seria prioritari de revisar manualment

1.Cream funció per obtenir dades

In [20]:
# funció per procesar clients

def procesar_client(un_client, nivells_seg):

    # definim les variables
    nom = un_client["nom"]
    edat = un_client["edat"]
    codi = un_client["codi"]

    # Busquem al diccionari de nivells de segur local
    info_seguros = nivells_seg[codi]

    categoria = info_seguros["categoria"]
    preu_base = info_seguros["preu_base"]
    frau = info_seguros["frau"]

    client_procesat = {    #creem un diccionari
        "nom": nom,
        "edat": edat,
        "categoria": categoria,
        "preu_base": preu_base,
        "probabilitat_frau": frau
    }
    return client_procesat

2. Càlcul del preu final

In [21]:
# funció per calcular el preu final

def calcular_preu_final(un_client_processat):
    preu_base = un_client_processat["preu_base"]
    edat = un_client_processat["edat"]

    # Apliquem la fórmula matemàtica i arrodonim a 2 decimals
    preu_final = round(preu_base * (1 + edat / 100), 2)

    un_client_processat["preu_final"] = preu_final
    return un_client_processat

3. definició de funció principal i mostra de dataframe

In [38]:
# definim funció principal
def main_seguros(clients, nivells_seguro):
    clients_finals = []

    for client in clients:
        # processem les dades bàsiques i de frau
        client_processat = procesar_client(client, nivells_seguro)

        # calculem el preu final i l'afegim al client
        client_amb_preu = calcular_preu_final(client_processat)

        # guardem resultats a llista nove
        clients_finals.append(client_amb_preu)

    return clients_finals

4.Mostrar dataframe final i anàlisis

In [39]:


def mostrar_dataframe(llista_clients, diccionari_seguros):
    # processem tots els clients amb la funció principal
    dades_finals_clients = main_seguros(llista_clients, diccionari_seguros)

    # creem datafram amb les dades calculades i procesades
    df_clients = pd.DataFrame(dades_finals_clients)

    # ordenem els clients per probabilitat de frau i preu final descendent
    df_ordenat = df_clients.sort_values(
        by=['probabilitat_frau', 'preu_final'],
        ascending=[False, False]
    )

    # mostrem el dataframe amb les columnes que demana l'enunciat
    print("DATAFRAME DE CLIENTS ORDENATS PER FRAU I PREU")
    print("-" * 75)

    columnes_finals = ['nom', 'edat', 'categoria', 'preu_base', 'preu_final', 'probabilitat_frau']
    display(df_ordenat[columnes_finals])

    print("\n" + "="*75 + "\n")

    # anàlisi i resposta a les preguntes
    client_max_frau = df_ordenat.iloc[0]  # el primer de la llista ordenada per frau és el de més risc
    client_max_preu = df_clients.loc[df_clients['preu_final'].idxmax()]  # el preu de pòlissa més alt

    print("APARTAT D'ANÀLISI I CONCLUSIONS")
    print("-" * 75)

    # Mostrem la probabilitat de frau (si és un decimal com 0.8, ho multipliquem per 100)
    frau_pct = client_max_frau['probabilitat_frau']
    if frau_pct <= 1.0:
        frau_display = f"{int(frau_pct * 100)}%"
    else:
        frau_display = f"{int(frau_pct)}%"

    print(f"» Client amb més probabilitat de frau: {client_max_frau['nom']} ({frau_display})")
    print(f"» Client amb el preu final més alt:   {client_max_preu['nom']} ({client_max_preu['preu_final']} €)")
    print(f"» Prioritat de revisió manual:         {client_max_frau['nom']} (Risc crític i alta probabilitat de frau)")


mostrar_dataframe(clients, nivells_seguro)

DATAFRAME DE CLIENTS ORDENATS PER FRAU I PREU
---------------------------------------------------------------------------

      nom  edat    categoria  preu_base  preu_final  probabilitat_frau
2  Isabel    55  Risc crític        500       775.0               0.30
1  Carlos    30     Risc alt        350       455.0               0.15
3   Jorge    40   Risc mitjà        200       280.0               0.05
0     Ana    42    Baix risc        120       170.4               0.01
4   Marta    28    Baix risc        120       153.6               0.01

===========================================================================

APARTAT D'ANÀLISI I CONCLUSIONS
---------------------------------------------------------------------------
» Client amb més probabilitat de frau: Isabel (30%)
» Client amb el preu final més alt:   Isabel (775.0 €)
» Prioritat de revisió manual:         Isabel (Risc crític i alta probabilitat de frau)

**Conclusions**

Amb aquest exercici hem creat una eina que permet classificar de forma ràpida i óptima els clients segons risc i probabilitat de frau.
D'aquesta manera, els tenim localitzats i podem pendre la decisió de negoci pertinent basant-nos en dades calculades.
Daltre banda, tambè ens permet fer un càlcul ràpid del cost de la pólissa segons edat.
Aquestes eines permeten optimitzar temps i recursos i ajuden a poder pendre decisions segons l'estratègia de negoci.